apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: horreum-run-payload
spec:
  params:
  - name: credentialsSecret
    description: the name of the Kubernetes secret that stores the credentials
    default: horreum-credentials
  - name: runid
    type: string
  steps:
    - name: upload
      image: quay.io/app-svc-perf/horreum-cli:0.0.1-SNAPSHOT
      env:
        - name: HORREUM_URI
          valueFrom:
            secretKeyRef:
              name: $(params.credentialsSecret)
              key: horreumUrl
        - name: HORREUM_USER
          valueFrom:
            secretKeyRef:
              name: $(params.credentialsSecret)
              key: username
        - name: HORREUM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.credentialsSecret)
              key: password
      args:
      - run
      - data
      - -i
      - $(params.runid)
